### ISSUE TITLE
Can u provide a sample docker-compose.yml file ?

### ISSUE THREAD

**Issue by shabeer-ali-m** [MetaiR/openlitespeed-php72-dockerfile#1]
Hi,

Can u provide docker-compose.yml file. or how to run your code ?

Thanks in advance.

**Comment by MetaiR** [comment]
@shabeer-ali-m 
hi, u just need to attach volume `/usr/local/lsws/Example/html` to a folder in ur system and put your php scripts in there

if this description was not enough please let me know so I create a docker-compose file example

**Comment by shabeer-ali-m** [comment]
Thanks got it :)
